# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FarmersMarket' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FarmersMarket
  pod 'Swinject', '2.0.0-beta.2'
  pod 'SwinjectStoryboard', '1.0.0-beta.2'
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'Mixpanel-swift'
  pod 'RxDataSources', '~> 1.0'

end
